---
services:
  nvidia-docker:

  jupyter:
    image: dldc
    # user: $UID
    volumes:
      - ./shared:/shared
    environment:
      - VIRTUAL_HOST=jupyter.${EXTERNAL_HOST}
      - VIRTUAL_PORT=8888
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
      - JUPYTER_PASSWORD_HASH=${JUPYTER_PASSWORD_HASH}
    ports:
      - "8888:8888"
      - "8097:8097"
    command: bash /root/.scripts/run_jupyter_lab.sh
    shm_size: '36gb'
